POST http://localhost:11434/api/generate
Content-Type: application/json

{
  "model": "llama3.2:1b",
  "prompt": "hi how are you?",
  "stream": false
}

###

# response
#{
#    "model": "llama3.2:1b",
#    "created_at": "2024-12-12T17:21:58.876374028Z",
#    "response": "I'm doing well, thanks for asking. I'm a large language model, so I don't have feelings or emotions like humans do, but I'm here and ready to help with any questions or tasks you may have. How about you? How's your day going?",
#    "done": true,
#    "done_reason": "stop",
#    "context": [],
#    "total_duration": 2092853254,
#    "load_duration": 15425340,
#    "prompt_eval_count": 28,
#    "prompt_eval_duration": 119000000,
#    "eval_count": 56,
#    "eval_duration": 1956000000
#}